name: dartdoc_json
description: Package for rendering dartdocs as JSON files.
version: 0.4.0
repository: https://github.com/bluefireteam/dartdoc_json
funding:
  - https://patreon.com/bluefireoss
  - https://www.buymeacoffee.com/bluefire

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.0.0
  args: ^2.6.0
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  flame_lint: ^1.2.1
  test: any

executables:
  dartdoc_json: main
